configure-cups (0.5.19) unstable; urgency=low
  * cupsconfig-kanotix was never in sidux, don't conflict with it.
  * make KDE and X optional, adjust depends/ recommends appropriately.

 -- Stefan Lippers-Hollmann <s.l-h@gmx.de>  Thu,  1 Mar 2007 12:17:23 +0100

diff --git a/cupsconfig b/cupsconfig
--- a/cupsconfig
+++ b/cupsconfig
@@ -1,7 +1,7 @@
 #!/bin/sh
 # cupsconfig - Start and configure cups
 # (C) Klaus Knopper Jun 2001
-# (C) 2004-2006 Stefan Lippers-Hollmann <s.l-h@gmx.de>
+# (C) 2004-2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
 
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 export PATH
@@ -19,23 +19,32 @@ fi
 
 for i in $(seq 1 20); do
 	sleep 2
-	lpstat -r >/dev/null 2>&1
-	error="$?"
-	if [ "$?" -eq 0 ]; then
-		if su-me kcmshell --nocrashhandler printers; then
-			su-me update-rc.d -f cupsys defaults
+	
+	if lpstat -r; then
+		if [ -x /usr/bin/kcmshell ]; then
+			if su-me kcmshell --nocrashhandler printers; then
+				su-me update-rc.d -f cupsys defaults
+			else
+				kcmshell --nocrashhandler printers
+			fi
 		else
-			kcmshell --nocrashhandler printers
+			su-me update-rc.d -f cupsys defaults
+			[ -z "$DISPLAY" ] && exec x-www-browser "http://127.0.0.1:631"
+			[ -n "$DISPLAY" ] && exec   www-browser "http://127.0.0.1:631"
 		fi
 
 		break
 	else
 		case "$LANG" in
 			es*)
-				exec xmessage '¡No puedo arrancar el servidor CUPS!'
+				[ -z "$DISPLAY" ] && [ -x /usr/bin/xmessage ] && exec xmessage '¡No puedo arrancar el servidor CUPS!'
+				echo '¡No puedo arrancar el servidor CUPS!' 1>&2
+				exit 1
 				;;
 			*)
-				exec xmessage 'Cannot start CUPS server!'
+				[ -z "$DISPLAY" ] && [ -x /usr/bin/xmessage ] && exec xmessage 'Cannot start CUPS server!'
+				echo 'Cannot start CUPS server!' 1>&2
+				exit 1
 				;;
 		esac
 	fi
