* switch from custom su-me to generic su-to-root, adapt dependencies and   menu files accordingly. * move desktop file into standard XDG hierarchy. * remove obsolete debian/dirs.

diff --git a/cupsconfig b/cupsconfig
--- a/cupsconfig
+++ b/cupsconfig
@@ -1,21 +1,24 @@
 #!/bin/sh
 # cupsconfig - Start and configure cups
 # (C) Klaus Knopper Jun 2001
-# (C) 2004-2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
+# (C) 2004-2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
 
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 export PATH
 
-[ "$(id -u)" -ne 0 ] && exec su-me "$0" "$@"
+if [ "$(id -u)" -ne 0 ]; then
+	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
+	printf "ERROR: $0 needs root capabilities, please start it as root\n\n" >&2
+fi
 
 HPLIP="$(pidof hpiod)"
 if [ -z "$HPLIP" ]; then
-	[ -x /etc/init.d/hplip ] && su-me /etc/init.d/hplip start
+	[ -x /etc/init.d/hplip ] && /etc/init.d/hplip start
 fi
 
 CUPSPID="$(pidof cupsd)"
 if [ -z "$CUPSPID" ]; then
-	[ -x /etc/init.d/cupsys ] && su-me /etc/init.d/cupsys start
+	[ -x /etc/init.d/cupsys ] && /etc/init.d/cupsys start
 	sleep 4
 fi
 
@@ -24,16 +27,16 @@ for i in $(seq 1 20); do
 
 	if lpstat -r; then
 		if [ -x /usr/bin/gnome-cups-manager ] ; then
-			su-me update-rc.d -f cupsys defaults
+			update-rc.d -f cupsys defaults
 			[ -n "$DISPLAY" ] && exec /usr/bin/gnome-cups-manager
 		elif [ -x /usr/bin/kcmshell ] ; then
-			if su-me kcmshell --nocrashhandler printers; then
-				su-me update-rc.d -f cupsys defaults
+			if kcmshell --nocrashhandler printers; then
+				update-rc.d -f cupsys defaults
 			else
 				kcmshell --nocrashhandler printers
 			fi
 		else
-			su-me update-rc.d -f cupsys defaults
+			update-rc.d -f cupsys defaults
 			[ -n "$DISPLAY" ] && exec x-www-browser "http://127.0.0.1:631"
 			[ -z "$DISPLAY" ] && exec   www-browser "http://127.0.0.1:631"
 		fi 
